title: <p align="center"> Sreedhar Gunda </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/Sreedhar103">GitHub</a>
  
  <br>   
  I am an upgrade student learning data science modile
  <br>
  </p>



theme: jekyll-theme-minimal
